---

spring:
  cloud:
    config:
      server:
        git:
          uri: ${vcap.services.configRepo.credentials.uri}
          # ONLY include username and pwd if the repo is private

          
security:
  user:
    name: admin
    password: adminadmin